import { Headphones, Mic2, Play } from "lucide-react";
import { NewsletterForm } from "@/components/newsletter-form";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";
export default async function PodcastsPage() {
  const episodes = await prisma.podcastEpisode.findMany({ where: { status: "published" }, orderBy: { createdAt: "asc" } });
  return <main><section className="bg-ink text-white"><div className="container-shell grid gap-8 py-12 lg:grid-cols-[1fr_320px]"><div><div className="text-xs font-black uppercase tracking-[.18em] text-violet-300">Coming Soon</div><h1 className="font-serif mt-3 text-balance text-4xl font-black sm:text-5xl">The conversations shaping the club industry.</h1><p className="mt-4 max-w-3xl text-lg leading-8 text-white/65">Operator briefings, GM conversations, project intelligence, and practical ClubOpsPro sessions—built for the commute between the clubhouse and the boardroom.</p></div><div className="flex items-center justify-center border border-white/15 bg-white/[.04] p-10"><Headphones className="h-24 w-24 text-violet-300" /></div></div></section><section className="container-shell py-10"><div className="section-rule"><div><div className="kicker">Show slate</div><h2 className="font-serif mt-1 text-3xl font-black">In Development</h2></div></div><div className="mt-6 grid gap-4 md:grid-cols-2">{episodes.map((episode, index) => <article key={episode.id} className="intelligence-card p-6"><div className="flex items-start justify-between gap-4"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-primary text-white">{index === 0 ? <Mic2 className="h-5 w-5" /> : <Play className="h-4 w-4" />}</div><span className="text-xs font-black uppercase tracking-wide text-primary">{episode.comingSoon ? "Coming soon" : "Listen now"}</span></div><div className="mt-5 text-xs font-black uppercase tracking-wider text-muted-foreground">{episode.showName}</div><h3 className="font-serif mt-2 text-2xl font-black">{episode.title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{episode.description}</p>{episode.duration ? <div className="mt-4 text-xs font-bold text-muted-foreground">Planned runtime: {episode.duration}</div> : null}</article>)}</div><div className="mt-10 grid gap-6 bg-primary p-7 text-white md:grid-cols-[1fr_420px]"><div><div className="text-xs font-black uppercase tracking-[.16em] text-emerald-200">Never miss the launch</div><h2 className="font-serif mt-2 text-3xl font-black">Join the ClubFlow briefing.</h2><p className="mt-2 text-sm leading-6 text-white/70">Podcast announcements and the industry intelligence you need now.</p></div><NewsletterForm /></div></section></main>;
}
