import type * as React from "react";
import type { AdminSectionKind } from "@/lib/admin-sections";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

export type StructuredFormValues = Record<string, string | number | boolean | null | undefined>;
export function AdminStructuredForm({ kind, action, values = {} }: { kind: Exclude<AdminSectionKind, "article">; action: (formData: FormData) => Promise<void>; values?: StructuredFormValues }) {
  const date = (name: string) => typeof values[name] === "string" ? values[name] as string : undefined;
  return <form action={action} className="grid gap-5 rounded-lg border bg-white p-5">
    <div className="rounded-md border border-primary/30 bg-primary/10 px-3 py-2 text-sm font-black text-primary">Content type locked to this section</div>
    <div className="grid gap-4 md:grid-cols-2">
      {kind === "job" ? <><Field name="title" label="Job Title" value={values.title} required /><Field name="clubName" label="Club" value={values.clubName} required /><Field name="city" label="City" value={values.city} /><Field name="state" label="State" value={values.state} /><Field name="url" label="Original Apply URL" value={values.url} type="url" /><Field name="postedAt" label="Publish Date" value={date("postedAt") ?? new Date().toISOString().slice(0, 10)} type="date" required /><Field name="expiresAt" label="Expiration Date" value={date("expiresAt")} type="date" /><Area name="description" label="Job Summary" value={values.description} /></> : null}
      {kind === "executiveMove" ? <><Field name="executive" label="Executive" value={values.executive} required /><Field name="newRole" label="New Role" value={values.newRole} required /><Field name="previousRole" label="Previous Role" value={values.previousRole} /><Field name="clubName" label="Club" value={values.clubName} required /><Field name="city" label="City" value={values.city} /><Field name="state" label="State" value={values.state} /><Field name="effectiveAt" label="Effective Date" value={date("effectiveAt")} type="date" /><Field name="publishedAt" label="Publish Date" value={date("publishedAt") ?? new Date().toISOString().slice(0,10)} type="date" required /><Area name="notes" label="Editorial Notes" value={values.notes} /></> : null}
      {kind === "ranking" ? <><Field name="category" label="Ranking Category" value={values.category} required /><Field name="rank" label="Rank" value={values.rank} type="number" min="1" required /><Field name="clubName" label="Club" value={values.clubName} required /><Field name="score" label="Score (0–100)" value={values.score} type="number" min="0" max="100" /><Field name="city" label="City" value={values.city} /><Field name="state" label="State" value={values.state} /><Field name="publishedAt" label="Publish Date" value={date("publishedAt") ?? new Date().toISOString().slice(0,10)} type="date" required /><Area name="rationale" label="Editorial Rationale" value={values.rationale} required /></> : null}
      {kind === "podcast" ? <><Field name="showName" label="Show Name" value={values.showName} required /><Field name="title" label="Episode Title" value={values.title} required /><Field name="duration" label="Duration" value={values.duration} placeholder="24 min" /><Field name="publishedAt" label="Publish Date" value={date("publishedAt")} type="date" /><Field name="audioUrl" label="Audio URL" value={values.audioUrl} type="url" /><Area name="description" label="Episode Description" value={values.description} required /><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" name="comingSoon" value="true" defaultChecked={values.comingSoon !== false} /> Coming soon</label></> : null}
    </div>
    <div className="grid gap-2"><Label htmlFor="status">Publishing Status</Label><select id="status" name="status" defaultValue={String(values.status ?? "draft")} className="h-10 rounded-md border bg-background px-3 text-sm"><option value="draft">Draft</option><option value="reviewed">Reviewed</option><option value="published">Published</option></select></div>
    <Button type="submit">{values.id ? "Update Content" : "Create Content"}</Button>
  </form>;
}
function Field({ label, name, value, ...props }: { label: string; name: string; value?: string | number | boolean | null } & Omit<React.InputHTMLAttributes<HTMLInputElement>, "defaultValue" | "value">) { return <div className="grid gap-2"><Label htmlFor={name}>{label}</Label><Input id={name} name={name} defaultValue={value == null || typeof value === "boolean" ? undefined : String(value)} {...props} /></div>; }
function Area({ label, name, value, required }: { label: string; name: string; value?: string | number | boolean | null; required?: boolean }) { return <div className="grid gap-2 md:col-span-2"><Label htmlFor={name}>{label}</Label><Textarea id={name} name={name} defaultValue={value == null || typeof value === "boolean" ? undefined : String(value)} required={required} /></div>; }
