import type * as React from "react";
import { Plus, Radar } from "lucide-react";
import { AdminTabs } from "@/components/admin-tabs";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { prisma } from "@/lib/prisma";
import { createDevelopment, createJob, createMove, createPodcast, createRanking } from "./actions";

export const dynamic = "force-dynamic";
export default async function IntelligenceAdminPage() {
  const [jobs, moves, developments, rankings, podcasts] = await Promise.all([prisma.jobPosting.findMany({ orderBy: { updatedAt: "desc" } }), prisma.executiveMove.findMany({ orderBy: { updatedAt: "desc" } }), prisma.developmentProject.findMany({ orderBy: { updatedAt: "desc" } }), prisma.rankingEntry.findMany({ orderBy: [{ category: "asc" }, { rank: "asc" }] }), prisma.podcastEpisode.findMany({ orderBy: { createdAt: "asc" } })]);
  return <main className="container-shell py-8"><AdminTabs /><div className="mb-6"><div className="flex items-center gap-2 text-xs font-bold uppercase text-primary"><Radar className="h-4 w-4" /> Structured Intelligence</div><h1 className="mt-1 text-3xl font-black">Manage Section Data</h1><p className="mt-2 text-sm text-muted-foreground">Create jobs, leadership moves, development projects, rankings, and podcast concepts. Editorial stories remain managed through Articles.</p></div><div className="mb-8 grid gap-3 sm:grid-cols-4"><Metric label="Jobs" value={jobs.length} /><Metric label="Moves" value={moves.length} /><Metric label="Developments" value={developments.length} /><Metric label="Rankings / Podcasts" value={rankings.length + podcasts.length} /></div><div className="grid gap-6 lg:grid-cols-2">
    <AdminForm title="Add Job" action={createJob}><Field name="title" label="Title" required /><Field name="clubName" label="Club" required /><div className="grid grid-cols-2 gap-3"><Field name="city" label="City" /><Field name="state" label="State" /></div><Field name="url" label="Original apply URL" type="url" /><Area name="description" label="Original short summary" /></AdminForm>
    <AdminForm title="Add Executive Move" action={createMove}><Field name="executive" label="Executive" required /><Field name="newRole" label="New role" required /><Field name="previousRole" label="Previous role" /><Field name="clubName" label="Club" required /><Area name="notes" label="Notes" /></AdminForm>
    <AdminForm title="Add Development" action={createDevelopment}><Field name="clubName" label="Club" required /><Field name="projectName" label="Project" required /><div className="grid grid-cols-2 gap-3"><Field name="budget" label="Budget" /><Field name="timeline" label="Timeline" /></div><Field name="status" label="Status" /><Area name="description" label="Description" /></AdminForm>
    <AdminForm title="Add Ranking Entry" action={createRanking}><Field name="category" label="Ranking category" required /><div className="grid grid-cols-2 gap-3"><Field name="rank" label="Rank" type="number" required /><Field name="score" label="Score (0–100)" type="number" /></div><Field name="clubName" label="Club" required /><Area name="rationale" label="Rationale" required /></AdminForm>
    <AdminForm title="Add Podcast Concept" action={createPodcast}><Field name="showName" label="Show" required /><Field name="title" label="Episode title" required /><Field name="duration" label="Planned duration" /><Area name="description" label="Description" required /></AdminForm>
  </div><section className="mt-8 intelligence-card p-5"><h2 className="text-xl font-black">Current structured records</h2><div className="mt-4 grid gap-5 md:grid-cols-3"><RecordList title="Jobs" items={jobs.map((item) => `${item.title} — ${item.clubName}`)} /><RecordList title="Executive Moves" items={moves.map((item) => `${item.executive} — ${item.newRole}`)} /><RecordList title="Developments" items={developments.map((item) => `${item.clubName} — ${item.projectName}`)} /></div></section></main>;
}
function Metric({ label, value }: { label: string; value: number }) { return <Card><CardContent className="p-4"><div className="text-xs font-bold uppercase text-muted-foreground">{label}</div><div className="mt-1 text-3xl font-black">{value}</div></CardContent></Card>; }
function AdminForm({ title, action, children }: { title: string; action: (formData: FormData) => Promise<void>; children: React.ReactNode }) { return <Card><CardContent className="p-5"><h2 className="mb-4 text-xl font-black">{title}</h2><form action={action} className="grid gap-3">{children}<Button type="submit"><Plus className="h-4 w-4" /> Add record</Button></form></CardContent></Card>; }
function Field({ label, name, ...props }: { label: string; name: string } & React.InputHTMLAttributes<HTMLInputElement>) { return <div className="grid gap-1.5"><Label htmlFor={name}>{label}</Label><Input id={name} name={name} {...props} /></div>; }
function Area({ label, name, required }: { label: string; name: string; required?: boolean }) { return <div className="grid gap-1.5"><Label htmlFor={name}>{label}</Label><Textarea id={name} name={name} required={required} /></div>; }
function RecordList({ title, items }: { title: string; items: string[] }) { return <div><div className="text-xs font-black uppercase tracking-wide text-primary">{title}</div><ul className="mt-2 space-y-2 text-sm text-muted-foreground">{items.slice(0, 8).map((item) => <li key={item}>{item}</li>)}</ul></div>; }
