import Link from "next/link";
import { format } from "date-fns";
import { ArrowUpRight, BriefcaseBusiness, MapPin } from "lucide-react";
import { prisma } from "@/lib/prisma";
import { formatLocation } from "@/lib/utils";

export const dynamic = "force-dynamic";
export default async function JobsPage() {
  const jobs = await prisma.jobPosting.findMany({ where: { status: "published" }, orderBy: { postedAt: "desc" } });
  const states = new Set(jobs.map((job) => job.state).filter(Boolean)).size;
  return <main><section className="border-b bg-ink text-white"><div className="container-shell grid gap-8 py-12 lg:grid-cols-[1fr_320px]"><div><div className="text-xs font-black uppercase tracking-[.18em] text-sky-300">Club Talent Market</div><h1 className="font-serif mt-3 text-4xl font-black sm:text-5xl">Leadership and operating roles across private clubs.</h1><p className="mt-4 max-w-3xl text-lg leading-8 text-white/65">A curated preview of notable opportunities—and a window into where clubs are investing in people and capabilities.</p></div><div className="grid grid-cols-2 gap-px border border-white/15 bg-white/15"><div className="bg-ink p-5"><div className="number-tabular text-4xl font-black">{jobs.length}</div><div className="mt-1 text-xs font-bold uppercase text-white/50">Open roles</div></div><div className="bg-ink p-5"><div className="number-tabular text-4xl font-black">{states}</div><div className="mt-1 text-xs font-bold uppercase text-white/50">Markets</div></div></div></div></section><section className="container-shell py-10"><div className="mb-6 flex flex-wrap gap-2">{["Executive Leadership", "Culinary", "Golf & Agronomy", "Membership", "Finance", "Technology"].map((label) => <span key={label} className="rounded-full border bg-white px-3 py-1.5 text-xs font-bold">{label}</span>)}</div><div className="grid gap-4">{jobs.map((job) => <article key={job.id} className="intelligence-card grid gap-4 p-5 md:grid-cols-[1fr_auto]"><div><div className="flex flex-wrap items-center gap-2 text-xs font-bold uppercase tracking-wide text-muted-foreground"><span>{format(job.postedAt, "MMM d, yyyy")}</span><span>·</span><span className="inline-flex items-center gap-1"><MapPin className="h-3.5 w-3.5" />{formatLocation(job.city, job.state)}</span></div><h2 className="font-serif mt-2 text-2xl font-black">{job.title}</h2><div className="mt-1 font-black text-primary">{job.clubName}</div>{job.description ? <p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground">{job.description}</p> : null}</div><div className="flex items-center">{job.url ? <Link href={job.url} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-sm border px-4 py-2 text-sm font-black no-underline hover:border-primary hover:text-primary">Apply at original source <ArrowUpRight className="h-4 w-4" /></Link> : <span className="text-xs text-muted-foreground">Application link pending</span>}</div></article>)}{!jobs.length ? <div className="border bg-white p-10 text-center"><BriefcaseBusiness className="mx-auto h-8 w-8 text-muted-foreground" /><p className="mt-3 text-muted-foreground">No roles are currently indexed.</p></div> : null}</div><p className="mt-6 text-xs leading-5 text-muted-foreground">ClubFlow displays short, original summaries and routes candidates to the original source. Demo listings are illustrative and not active vacancies.</p></section></main>;
}
